stan: Set the upper bound of reports
Increasing this causes exceptions:
	Exception: Exception: neg_binomial_2_rng: Random number that came from gamma distribution is 1.45548e+09, but must be less than 1.07374e+09

So, reorganize the code and restore the old limit.

Signed-off-by: Hamada S. Badr <hamada.s.badr@gmail.com>